### ISSUE TITLE
API returns {'message': 'not found'}

### ISSUE THREAD

**Issue by JetZhouUWO** [name-ethnicity-classifier/nec-api-server#1]
Hi there,

I hope this message finds you well.

I am currently working on a project that needs some help in identifying someone's ethnicity based on their names. And your web appears on the top search results. This looks fantastic!!

While I am trying to use the API, I have met some issues and hopefully, you may offer some help! It would be truly appreciated.

While I followed your instruction on your API website, https://www.name-to-ethnicity.com/api-documentation, I got a return as ```{'message': 'not found'}```, I am not sure what happened, could you please guide me on this?

BTW, small places that may cause issues:
```response = request.post(api_url, data=body, headers=headers)```
I believe it should be ```request**s**.post()```.

Once again, this is awesome and hopefully I can also benefit from your work.

**Comment by theopfr** [comment]
Hey, thanks for pointing out the typo at "requests". I just found another typo: In the example code it says "Autorization" instead of "Authorization". I will have to fix that. But I dont know how you got the "message": "not found" error. That could happen if you try to access an endpoint which doesnt exist or try to do a GET request on a POST endpoint.
Can you try the following code?:

```python
import requests

base_url = "https://api.name-to-ethnicity.com"
endpoint = "/classify-names"

headers = {
    "Authorization": "Bearer <token>",
    "Email": "<email>",
}

body = {
    "modelName": "chinese_and_else",
    "names": ["Theodor Peifer", "Liu Cixin"]
}


response = requests.post(base_url + endpoint, data=body, headers=headers)

print(response.status_code)
print(response.json())
```

**Comment by JetZhouUWO** [comment]
Hey Theo, this works. And I just tested it on my own name list and it also works! Appreciate your quick response!
